services:
  - type: web
    name: User-Info # the name of this service, eg your app name
    env: static # this app is written in angular so choose static
    plan: free # make sure to set this to free or you'll get billed $$$
    buildCommand: "./bin/render-build.sh" # we already created these two files for you
    startCommand: "./bin/render-start.sh"
